// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByeaBBzmLrb4ozK1UVkIbNivcKIyxsvME',
    appId: '1:950597605784:web:dc0eec3ca988372796f3ed',
    messagingSenderId: '950597605784',
    projectId: 'adaptive-sleep-checker',
    authDomain: 'adaptive-sleep-checker.firebaseapp.com',
    storageBucket: 'adaptive-sleep-checker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZiwaDDR7X_2B_wXBqvwvyRyhh2HBpS4Y',
    appId: '1:950597605784:android:f3d66cc90ec4b5bd96f3ed',
    messagingSenderId: '950597605784',
    projectId: 'adaptive-sleep-checker',
    storageBucket: 'adaptive-sleep-checker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB98vrcRYquA9WvXxYsmb-vr5hzl4Flo0E',
    appId: '1:950597605784:ios:e20f23bbf49a061b96f3ed',
    messagingSenderId: '950597605784',
    projectId: 'adaptive-sleep-checker',
    storageBucket: 'adaptive-sleep-checker.firebasestorage.app',
    androidClientId: '950597605784-ar6dbuu4csgq29cn4vhpmra2u016sqch.apps.googleusercontent.com',
    iosClientId: '950597605784-8hpq29qg9fr8ufk25ltr3n8pk0igq3oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.adaptiveSleepChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB98vrcRYquA9WvXxYsmb-vr5hzl4Flo0E',
    appId: '1:950597605784:ios:e20f23bbf49a061b96f3ed',
    messagingSenderId: '950597605784',
    projectId: 'adaptive-sleep-checker',
    storageBucket: 'adaptive-sleep-checker.firebasestorage.app',
    iosBundleId: 'com.example.adaptiveSleepChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByeaBBzmLrb4ozK1UVkIbNivcKIyxsvME',
    appId: '1:950597605784:web:fb1fc7608afd47aa96f3ed',
    messagingSenderId: '950597605784',
    projectId: 'adaptive-sleep-checker',
    authDomain: 'adaptive-sleep-checker.firebaseapp.com',
    storageBucket: 'adaptive-sleep-checker.firebasestorage.app',
  );
}
//test